### ISSUE TITLE
can this be used standalone?

### ISSUE THREAD

**Issue by cekvenich2** [ficusjs/ficusjs-event-bus#1]
Is there an example of using it standalone?

ps: I am big fan of your ficus js! I do wish it was much lighter/smaller.

**Comment by ducksoupdev** [comment]
Thanks for your comment, glad you like FicusJS, we're big fans of keeping things lightweight and simple.

The event bus can be used standalone. You can import it as an ES module from a CDN like skypack or use the NPM package to include it in your application.

How are you thinking about using it?

**Comment by roaster-vicc** [comment]
I'd rather private DM you? Like email or linkedin - I sent you an invite
there from Vic Cekvenich.

**Comment by roaster-vicc** [comment]
Do you have suggestion how to reach you?

**Comment by ducksoupdev** [comment]
You can email us dev at ficusjs.org
