### ISSUE TITLE
Feature requests for robust event system:

### ISSUE THREAD

**Issue by cekvenich2** [ficusjs/ficusjs-event-bus#2]
Thanks for a nice lib, we are now using fixus for several clients at AXthe.net.
I’d like to use your even system, we need:

1. fireOnce(), makes it a bit easier to avoid memory leaks.
2. Global singleton page instance of the event bus.. So all components can talk to each other safely. And an example please.
3. List registered listeners()
4. A bit more docs here.
5. Be able to have event sent, before there is a listener added. (and listener catches it). Sometimes it is hard to control the order. This makes it simple to use.
(sample implementation of that: https://github.com/intuition-dev/mbToolBelt/blob/master/eventFlux/EventFlux.ts )
Of course this needs an example/test case.

Cheers!

**Comment by cekvenich2** [comment]
As part of #1 above, a listenOnce() please.

**Comment by ducksoupdev** [comment]
FicusJS v3.7.0 now includes the updated `@ficusjs/event-bus` v1.1.1. This version includes:

- Subscription options can be passed to the `subscribe` method - this currently has `fireOnce` option to ensure the callback is only called once
- A new method named `getSubscribers` which returns a Map of subscribers

Full docs can be found at https://docs.ficusjs.org/event-bus/

The event bus is a singleton by default, multiple instances cannot be created.
