### ISSUE TITLE
example via cdn?

### ISSUE THREAD

**Issue by cekvenich2** [ficusjs/ficusjs-event-bus#3]
Can I have an example of using the event bus via cdn please?

(also domain https://www.ficusjs.org is blank - should redirect to docs)

**Comment by ducksoupdev** [comment]
The event bus docs here provides an example of importing via CDN - https://docs.ficusjs.org/event-bus/example/

Also, https://www.ficusjs.org now has a new basic site up and running :)

**Comment by cekvenich2** [comment]
cool. thx
